language: ruby
dist: bionic

sudo: required
services:
  - docker

notifications:
  email: false

cache: bundler

before_install:
  # Update rubygems so that bundler will work (for ruby 2.5.3)
  - yes | gem update --system

rvm:
  - 2.5.3 # deployed
  - 2.6.4 # latest

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up bundle install
