language: ruby
dist: bionic

sudo: required
services:
  - docker

notifications:
  email: false

cache: bundler

rvm:
  - 2.6.5 # deployed
  - 2.7.0 # latest

jobs:
  allow_failures:
  - rvm: 2.7.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up bundle install
