version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@2.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-gem:
          name: test
          before-test:
            - run:
                name: install rsync
                command: sudo apt update && sudo apt install -y rsync
            - run:
                name: Install libvips
                command: sudo apt-get update && sudo apt-get install -y libvips
