version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - ruby-rails/test-gem:
          name: test
          context: dlss
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
          before-test:
            - run:
                name: install rsync
                command: sudo apt update && sudo apt install -y rsync
            - run:
                name: Install libvips
                command: sudo apt-get update && sudo apt-get install -y libvips
            - run:
                name: Install exiftool
                command: curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
