content-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 50

descriptive-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 50

rights-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 50

technical-metadata:
    prerequisite: content-metadata
    batch_limit: 1000
    error_limit: 50

remediate-object:
    prerequisite:
      - content-metadata
      - descriptive-metadata
      - rights-metadata
	  - technical-metadata
    batch_limit: 1000
    error_limit: 50

provenance-metadata:
    prerequisite:
	  - remediate-object
	  - shelve
    batch_limit: 1000
    error_limit: 50

shelve:
    prerequisite: remediate-object
    batch_limit: 1000
    error_limit: 50

publish:
    prerequisite: shelve
    batch_limit: 1000
    error_limit: 10

sdr-ingest-transfer:
    prerequisite: 
      - provenance-metadata

    batch_limit: 1000
    error_limit: 50

end-accession:
    prerequisite: 
      - sdr-ingest-received
	  - publish
    batch_limit: 1000
    error_limit: 50

repository: dor
