content-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 10

descriptive-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 10
    
rights-metadata:
    prerequisite: start-accession
    batch_limit: 1000
    error_limit: 10

technical-metadata:
    prerequisite: content-metadata
    batch_limit: 1
    error_limit: 5

provenance-metadata:
    prerequisite: 
      - content-metadata
      - descriptive-metadata
      - rights-metadata
      - technical-metadata
    batch_limit: 1
    error_limit: 5

remediate-object:
    prerequisite: 
      - content-metadata
      - descriptive-metadata
      - rights-metadata
    batch_limit: 100
    error_limit: 5
    
shelve:
    prerequisite: remediate-object
    batch_limit: 1
    error_limit: 5

publish:
    prerequisite: shelve
    batch_limit: 1000
    error_limit: 10

sdr-ingest-transfer:
    prerequisite: provenance-metadata
    batch_limit: 1
    error_limit: 5

cleanup:
    prerequisite:
      - sdr:sdrIngestWF:complete-deposit
      - dor:accessionWF:shelve
    batch_limit: 1
    error_limit: 5

repository: dor

