"accessionWF_default,assemblyWF_default,disseminationWF_default,etdSubmitWF_default,goobiWF_default,releaseWF_default,accessionWF_low,assemblyWF_low,disseminationWF_low,etdSubmitWF_low,goobiWF_low,releaseWF_low": 10
"assemblyWF_jp2": 1
