dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token
  token_header: 'X-Auth'

repository_manager:
  email: bergeraj@stanford.edu

smtp:
  address: 'smtp.stanford.edu'
  port: '25'
  enable_starttls_auto: true
  authentication: :plain # :plain, :login, :cram_md5, no auth by default
  domain: 'localhost.localdomain' # the HELO domain provided by the client to the server
