# Graveyard Admin Policy
graveyard_admin_policy:
  druid: 'druid:kg712km1576' # This value varies by environment and is managed in shared_configs

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token

assembly:
  root_dir:  # directories to search for content that should be acted upon by the robots
    - spec/test_input
    - spec/test_input2
  stub_cm_file_name: stubContentMetadata.xml # the name of the stub contentMetadata file
  # (e.g. oo000oo0001_00_001.tif and oo000oo0001_05_001.jp2, then a "false" setting here would NOT generate a new jp2 even though there is no filename clash)
  tmp_folder: /tmp # tmp file location for jp2-create and imagemagick

sdr:
  local_workspace_root: /dor/workspace
  abbyy_ticket_path: /tmp
  abbyy_output_path: /tmp
  abbyy_result_path: /tmp
  abbyy_exception_path: /tmp

tech_md_service:
  url: 'https://dor-techmd-test.stanford.test'
  token: 'rake-generate-token-me'

# Used by Dor::DigitalStacksService, Dor::PublishMetadataService, and Dor::ShelvingService
stacks:
  local_workspace_root: ~

workflow:
  url: https://example.com/workflow/
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60

redis:
  url: ~

purl_url: 'https://purl-example.stanford.edu'

preservation_catalog:
  url: 'https://preservation-catalog-stage-01.stanford.edu'
  token: 'mint-token-with-target-preservation-catalog-rake-generate-token'
