# frozen_string_literal: true

require 'common/base'
require 'accession/abstract_metadata'
require 'accession/content_metadata'
require 'accession/descriptive_metadata'
require 'accession/end_accession'
require 'accession/provenance_metadata'
require 'accession/publish'
require 'accession/remediate_object'
require 'accession/rights_metadata'
require 'accession/sdr_ingest_transfer'
require 'accession/shelve'
require 'accession/technical_metadata'
require 'accession/reset_workspace'
require 'dissemination/cleanup'
require 'goobi/goobi_notify'
require 'release/release_members'
require 'release/release_publish'
require 'release/update_marc'
require 'dor/release'
require 'assembly/accessioning_initiate'
require 'assembly/checksum_compute'
require 'assembly/exif_collect'
require 'assembly/jp2_create'
require 'assembly/content_metadata_create'
require 'dor/assembly'
